name: Unit Test

# Run unit tests on every push or pull request, to main or develop
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

# Generate an Xcode project, and run unit tests on an iPhone 12
jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        platform:
          - iOS

    steps:
    - uses: actions/checkout@v2.3.4
     - use: mxcl/xcodebuild@v1
        with:
          platform: ${{ matrix.platform }}
          action: test
          
    #- name: Run tests
    #  run: xcodebuild -scheme KukaiCoreSwift test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'