name: Unit Test

# Run unit tests on every push or pull request, to main or develop
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

# Generate an Xcode project, and run unit tests on an iPhone 12
jobs:
  build:
    runs-on: macOS-latest

    steps:
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 12' -scheme 'KukaiCoreSwift-Package'