name: Unit Test

# Run unit tests on every push or pull request, to main or develop
on:
  push:
    branches:
      - main
      - develop
      - feature/xcode13
  pull_request:
    branches:
      - main
      - develop

# Checkout the code, and run mxcl's xcodebuild action to run the unit tests
jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        platform:
          - iOS
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: mxcl/xcodebuild@v1.7.0
        with:
          platform: ${{ matrix.platform }}
          action: test
          scheme: KukaiCoreSwift
          code-coverage: true
          upload-logs: always
      
      #- name: Test
      #  run: xcodebuild -scheme KukaiCoreSwift test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' -enableCodeCoverage YES -resultBundlePath "../../xcode-$GITHUB_RUN_ID.xcresult"
      #
      #- name: Upload results
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: "results-$GITHUB_RUN_ID.xcresult"
      #    path: "/Users/runner/work/xcode-$GITHUB_RUN_ID.xcresult"
